# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GaNology_remote_control.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        self.menuDevices = QtWidgets.QMenu(self.menubar)
        self.menuDevices.setObjectName("menuDevices")
        self.menuSignal_Generator = QtWidgets.QMenu(self.menuDevices)
        self.menuSignal_Generator.setObjectName("menuSignal_Generator")
        self.menuVector_Network_Analyzer = QtWidgets.QMenu(self.menuDevices)
        self.menuVector_Network_Analyzer.setObjectName("menuVector_Network_Analyzer")
        self.menuSpectrum_Analyzer = QtWidgets.QMenu(self.menuDevices)
        self.menuSpectrum_Analyzer.setObjectName("menuSpectrum_Analyzer")
        self.menuTestBenches = QtWidgets.QMenu(self.menubar)
        self.menuTestBenches.setObjectName("menuTestBenches")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionSMB100A = QtWidgets.QAction(MainWindow)
        self.actionSMB100A.setObjectName("actionSMB100A")
        self.actionSMA100B = QtWidgets.QAction(MainWindow)
        self.actionSMA100B.setObjectName("actionSMA100B")
        self.actionZNB40 = QtWidgets.QAction(MainWindow)
        self.actionZNB40.setObjectName("actionZNB40")
        self.actionFSV7G = QtWidgets.QAction(MainWindow)
        self.actionFSV7G.setObjectName("actionFSV7G")
        self.actionFSV30G = QtWidgets.QAction(MainWindow)
        self.actionFSV30G.setObjectName("actionFSV30G")
        self.actionS_para_Measurement = QtWidgets.QAction(MainWindow)
        self.actionS_para_Measurement.setObjectName("actionS_para_Measurement")
        self.actionNF_Sourcepull = QtWidgets.QAction(MainWindow)
        self.actionNF_Sourcepull.setObjectName("actionNF_Sourcepull")
        self.menuSignal_Generator.addAction(self.actionSMB100A)
        self.menuSignal_Generator.addAction(self.actionSMA100B)
        self.menuVector_Network_Analyzer.addAction(self.actionZNB40)
        self.menuSpectrum_Analyzer.addAction(self.actionFSV7G)
        self.menuSpectrum_Analyzer.addAction(self.actionFSV30G)
        self.menuDevices.addAction(self.menuSignal_Generator.menuAction())
        self.menuDevices.addAction(self.menuVector_Network_Analyzer.menuAction())
        self.menuDevices.addAction(self.menuSpectrum_Analyzer.menuAction())
        self.menuTestBenches.addAction(self.actionS_para_Measurement)
        self.menuTestBenches.addAction(self.actionNF_Sourcepull)
        self.menubar.addAction(self.menuDevices.menuAction())
        self.menubar.addAction(self.menuTestBenches.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuDevices.setTitle(_translate("MainWindow", "Devices"))
        self.menuSignal_Generator.setTitle(_translate("MainWindow", "Signal Generator"))
        self.menuVector_Network_Analyzer.setTitle(_translate("MainWindow", "Vector Network Analyzer"))
        self.menuSpectrum_Analyzer.setTitle(_translate("MainWindow", "Spectrum Analyzer"))
        self.menuTestBenches.setTitle(_translate("MainWindow", "TestBenches"))
        self.actionSMB100A.setText(_translate("MainWindow", "SMB100A"))
        self.actionSMA100B.setText(_translate("MainWindow", "SMA100B"))
        self.actionZNB40.setText(_translate("MainWindow", "ZNB40"))
        self.actionFSV7G.setText(_translate("MainWindow", "FSV7G"))
        self.actionFSV30G.setText(_translate("MainWindow", "FSV30G"))
        self.actionS_para_Measurement.setText(_translate("MainWindow", "S-para Measurement"))
        self.actionNF_Sourcepull.setText(_translate("MainWindow", "NF Sourcepull"))
